using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlineLearningApp.Data;
using OnlineLearningApp.Data.Services;
using OnlineLearningApp.Models;
using System.Security.Claims;

namespace OnlineLearningApp.Controllers;

public class CourseController : Controller
{
    private readonly ICourseService _service;
    private readonly ICourseCompletionService _completionService;
    private readonly OnlineLearningAppDbContext _context;
    public CourseController(ICourseService service, ICourseCompletionService completionService, OnlineLearningAppDbContext context) { _service = service; _completionService = completionService; _context = context; }
    [AllowAnonymous] public async Task<IActionResult> Index() => View(await _service.GetAllAsync());
    [AllowAnonymous] public async Task<IActionResult> Filter(string? searchString){var courses=await _service.GetAllAsync();if(!string.IsNullOrWhiteSpace(searchString)){var term=searchString.Trim();courses=courses.Where(c=>c.CourseName.Contains(term,StringComparison.CurrentCultureIgnoreCase)||c.Description.Contains(term,StringComparison.CurrentCultureIgnoreCase)||c.Category.GetDescription().Contains(term,StringComparison.CurrentCultureIgnoreCase)).ToList();}return View("Index",courses);}
    [AllowAnonymous] public async Task<IActionResult> Details(int id){var course=await _context.Courses.AsNoTracking().Include(c=>c.Instructor).Include(c=>c.Modules).ThenInclude(m=>m.Quizzes).FirstOrDefaultAsync(c=>c.Id==id);if(course is null)return View("NotFound");var enrolled=false;var studentId=User.FindFirstValue(ClaimTypes.NameIdentifier);if(!string.IsNullOrWhiteSpace(studentId))enrolled=await _context.StudentCourses.AnyAsync(sc=>sc.StudentId==studentId&&sc.CourseId==course.Id);ViewBag.IsEnrolled=enrolled;return View(course);}
    [Authorize(Roles=UserRoles.Student)] public async Task<IActionResult> Learn(int id){var studentId=User.FindFirstValue(ClaimTypes.NameIdentifier);if(string.IsNullOrWhiteSpace(studentId))return Challenge();var enrollment=await _context.StudentCourses.FirstOrDefaultAsync(sc=>sc.StudentId==studentId&&sc.CourseId==id);if(enrollment is null){TempData["Error"]="Please enroll in this course before starting the lessons.";return RedirectToAction(nameof(Details),new{id});}var course=await _context.Courses.AsNoTracking().AsSplitQuery().Include(c=>c.Instructor).Include(c=>c.Modules.OrderBy(m=>m.ModuleId)).ThenInclude(m=>m.Quizzes).Include(c=>c.Modules).ThenInclude(m=>m.Materials).FirstOrDefaultAsync(c=>c.Id==id);if(course is null)return View("NotFound");var completedModuleIds=await _context.StudentModuleProgress.AsNoTracking().Where(p=>p.StudentId==studentId&&p.CompletedAt!=null).Select(p=>p.ModuleId).ToListAsync();var completedCount=course.Modules.Count(m=>completedModuleIds.Contains(m.ModuleId));ViewBag.CompletedModuleIds=completedModuleIds;ViewBag.CompletedModuleCount=completedCount;ViewBag.ProgressPercentage=course.Modules.Count==0?0:(int)Math.Round(completedCount*100m/course.Modules.Count);ViewBag.IsCourseCompleted=enrollment.CompletedAt.HasValue;ViewBag.HasPaid=await _context.Orders.AnyAsync(o=>o.AccountId==studentId&&o.PaymentStatus==PaymentStatus.Paid&&o.OrderItems.Any(i=>i.CourseId==id));ViewBag.Capstone=await _context.CapstoneSubmissions.AsNoTracking().FirstOrDefaultAsync(s=>s.StudentId==studentId&&s.CourseId==id);return View(course);}
    [HttpPost,ValidateAntiForgeryToken,Authorize(Roles=UserRoles.Student)] public async Task<IActionResult> CompleteModule(int courseId,int moduleId){var studentId=User.FindFirstValue(ClaimTypes.NameIdentifier);if(string.IsNullOrWhiteSpace(studentId))return Challenge();var enrollment=await _context.StudentCourses.FirstOrDefaultAsync(sc=>sc.StudentId==studentId&&sc.CourseId==courseId);if(enrollment is null){TempData["Error"]="You must be enrolled in this course before completing lessons.";return RedirectToAction(nameof(Details),new{id=courseId});}if(!await _context.Modules.AnyAsync(m=>m.ModuleId==moduleId&&m.CourseId==courseId))return NotFound();var progress=await _context.StudentModuleProgress.FirstOrDefaultAsync(p=>p.StudentId==studentId&&p.ModuleId==moduleId);if(progress is null)_context.StudentModuleProgress.Add(new StudentModuleProgress{StudentId=studentId,ModuleId=moduleId,StartedAt=DateTime.UtcNow,CompletedAt=DateTime.UtcNow});else progress.CompletedAt??=DateTime.UtcNow;await _context.SaveChangesAsync();var completion=await _completionService.EvaluateAsync(studentId,courseId);TempData["Success"]=completion.IsCompleted?"Course completed. Your certificate is now available.":completion.ModulesCompleted?(completion.QuizzesCompleted?(completion.CapstoneCompleted?"All course requirements are complete.":"Modules and assessments are complete. Submit and obtain capstone approval to unlock your certificate."):"All modules are complete. Pass the required checkpoint assessments to unlock your certificate."):"Module marked as complete. Keep going!";return RedirectToAction(nameof(Learn),new{id=courseId});}
    [HttpPost,ValidateAntiForgeryToken,Authorize(Roles=UserRoles.Student)] public async Task<IActionResult> Enroll(int id){var studentId=User.FindFirstValue(ClaimTypes.NameIdentifier);if(string.IsNullOrWhiteSpace(studentId))return Challenge();var course=await _context.Courses.AsNoTracking().FirstOrDefaultAsync(c=>c.Id==id);if(course is null)return View("NotFound");if(!await _context.StudentCourses.AnyAsync(sc=>sc.StudentId==studentId&&sc.CourseId==id)){_context.StudentCourses.Add(new StudentCourse{StudentId=studentId,CourseId=id,EnrollmentDate=DateTime.UtcNow});await _context.SaveChangesAsync();TempData["Success"]=$"You are now enrolled in {course.CourseName}.";}else TempData["Success"]="You are already enrolled in this course.";return RedirectToAction(nameof(Learn),new{id});}
    [Authorize(Roles=UserRoles.Admin)] public async Task<IActionResult> Create(){await PopulateCourseDropdownsAsync();return View();}
    [HttpPost,Authorize(Roles=UserRoles.Admin)] public async Task<IActionResult> Create(NewCourseViewModel course){await ValidateInstructorAsync(course.InstructorId);if(!ModelState.IsValid){await PopulateCourseDropdownsAsync(course.InstructorId,course.Category);return View(course);}await _service.AddNewCourseAsync(course);TempData["Success"]=$"Course '{course.CourseName}' was created successfully.";return RedirectToAction(nameof(Index));}
    [Authorize(Roles=UserRoles.Admin)] public async Task<IActionResult> Edit(int id){var d=await _service.GetCourseByIdAsync(id);if(d is null)return View("NotFound");var r=new NewCourseViewModel{Id=d.Id,CourseName=d.CourseName,Description=d.Description,Price=d.Price,StartDate=d.StartDate,EndDate=d.EndDate,ImageURL=d.ImageURL,Category=d.Category,Status=d.Status,InstructorId=d.InstructorId,RequireAllQuizzesPassed=d.RequireAllQuizzesPassed,ModuleIds=d.Courses_Modules.Select(n=>n.ModuleId).ToList()};await PopulateCourseDropdownsAsync(r.InstructorId,r.Category);return View(r);}
    [HttpPost,Authorize(Roles=UserRoles.Admin)] public async Task<IActionResult> Edit(int id,NewCourseViewModel course){if(id!=course.Id)return View("NotFound");await ValidateInstructorAsync(course.InstructorId);if(!ModelState.IsValid){await PopulateCourseDropdownsAsync(course.InstructorId,course.Category);return View(course);}await _service.UpdateCourseAsync(course);TempData["Success"]=$"Course '{course.CourseName}' was updated successfully.";return RedirectToAction(nameof(Index));}
    private async Task ValidateInstructorAsync(string instructorId){if(string.IsNullOrWhiteSpace(instructorId)){ModelState.AddModelError(nameof(NewCourseViewModel.InstructorId),"Please select an instructor.");return;}var roleId=await _context.Roles.Where(r=>r.Name==UserRoles.Instructor).Select(r=>r.Id).FirstOrDefaultAsync();if(roleId is null||!await _context.UserRoles.AnyAsync(ur=>ur.UserId==instructorId&&ur.RoleId==roleId))ModelState.AddModelError(nameof(NewCourseViewModel.InstructorId),"The selected account is not an instructor.");}
    private async Task PopulateCourseDropdownsAsync(string? selectedInstructorId=null,CourseCategory? selectedCategory=null){var d=await _service.GetNewCourseDropdownsValues();ViewBag.Categories=d.Categories.Select(c=>new SelectListItem{Value=((int)c).ToString(),Text=c.GetDescription(),Selected=selectedCategory.HasValue&&c==selectedCategory.Value}).ToList();ViewBag.Instructors=d.Instructors.Select(i=>new SelectListItem{Value=i.UserId,Text=i.FullName,Selected=i.UserId==selectedInstructorId}).ToList();}
}
