using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OnlineLearningApp.Data;
using OnlineLearningApp.Data.Cart;
using OnlineLearningApp.Data.Services;
using OnlineLearningApp.Models;
using System.Security.Claims;

namespace OnlineLearningApp.Controllers;

[Authorize(Roles = UserRoles.Admin + "," + UserRoles.Student)]
public class OrdersController : Controller
{
    private readonly ICourseService _courseService; private readonly ShoppingCart _shoppingCart; private readonly IOrderService _ordersService; private readonly OnlineLearningAppDbContext _context; private readonly IPaymentGateway _paymentGateway; private readonly TimeProvider _clock;
    public OrdersController(ICourseService courseService, ShoppingCart shoppingCart, IOrderService ordersService, OnlineLearningAppDbContext context, IPaymentGateway paymentGateway, TimeProvider clock){_courseService=courseService;_shoppingCart=shoppingCart;_ordersService=ordersService;_context=context;_paymentGateway=paymentGateway;_clock=clock;}
    [HttpGet,Authorize(Roles=UserRoles.Student)] public async Task<IActionResult> GetCartItemCount()=>Json(new{count=(await _shoppingCart.GetShoppingCartItemsAsync()).Sum(i=>i.Amount)});
    [HttpGet] public async Task<IActionResult> Index(){var userId=User.FindFirstValue(ClaimTypes.NameIdentifier);if(string.IsNullOrWhiteSpace(userId))return Challenge();var isAdmin=User.IsInRole(UserRoles.Admin);return View(await _ordersService.GetOrdersByUserIdAndRoleAsync(userId,isAdmin?UserRoles.Admin:UserRoles.Student));}
    [HttpGet,Authorize(Roles=UserRoles.Student)] public async Task<IActionResult> ShoppingCart(){var items=await _shoppingCart.GetShoppingCartItemsAsync();return View(new ShoppingCartViewModel{ShoppingCart=_shoppingCart,ShoppingCartItems=items,ShoppingCartTotal=await _shoppingCart.GetShoppingCartTotalAsync()});}
    [HttpPost,ValidateAntiForgeryToken,Authorize(Roles=UserRoles.Student)] public async Task<IActionResult> AddItemToShoppingCart(int id){var item=await _courseService.GetCourseByIdAsync(id);if(item is null)return NotFound();await _shoppingCart.AddItemToCartAsync(item);TempData["Success"]="Course added to your cart. Payment is required before graded assessments and certification.";return RedirectToAction(nameof(ShoppingCart));}
    [HttpPost,ValidateAntiForgeryToken,Authorize(Roles=UserRoles.Student)] public async Task<IActionResult> RemoveItemFromShoppingCart(int id){var item=await _courseService.GetCourseByIdAsync(id);if(item is null)return NotFound();await _shoppingCart.RemoveItemFromCartAsync(item);return RedirectToAction(nameof(ShoppingCart));}
    [HttpPost,ValidateAntiForgeryToken,Authorize(Roles=UserRoles.Student)] public async Task<IActionResult> CompleteOrder(){var items=await _shoppingCart.GetShoppingCartItemsAsync();if(items.Count==0){TempData["Error"]="Your cart is empty.";return RedirectToAction(nameof(ShoppingCart));}var userId=User.FindFirstValue(ClaimTypes.NameIdentifier);var email=User.FindFirstValue(ClaimTypes.Email);if(string.IsNullOrWhiteSpace(userId)||string.IsNullOrWhiteSpace(email))return Challenge();await _ordersService.StoreOrderAsync(items,userId,email);var order=await _context.Orders.Include(o=>o.OrderItems).Where(o=>o.AccountId==userId).OrderByDescending(o=>o.Id).FirstAsync();order.PaymentStatus=PaymentStatus.Pending;order.PaymentReference=$"TBA-{order.Id}-{Guid.NewGuid().ToString("N")[..12].ToUpperInvariant()}";await _context.SaveChangesAsync();var callbackUrl=Url.Action(nameof(PaymentCallback),"Orders",null,Request.Scheme)!;try{var checkoutUrl=await _paymentGateway.InitializeAsync(email,order.TotalAmount,order.PaymentReference,callbackUrl);await _shoppingCart.ClearShoppingCartAsync();return Redirect(checkoutUrl);}catch(InvalidOperationException ex){TempData["Error"]=ex.Message;return RedirectToAction(nameof(Index));}}
    [AllowAnonymous,HttpGet] public async Task<IActionResult> PaymentCallback(string? reference){if(string.IsNullOrWhiteSpace(reference)){TempData["Error"]="Payment reference was not provided.";return RedirectToAction(nameof(Index));}var order=await _context.Orders.FirstOrDefaultAsync(o=>o.PaymentReference==reference);if(order is null)return NotFound();PaymentVerificationResult verification;try{verification=await _paymentGateway.VerifyAsync(reference);}catch{TempData["Error"]="We could not verify the payment yet. Please check your order status or contact support.";return RedirectToAction(nameof(Index));}if(verification.IsSuccessful&&Math.Abs(verification.AmountNaira-order.TotalAmount)<0.01m){order.PaymentStatus=PaymentStatus.Paid;order.PaidAt=_clock.GetUtcNow().UtcDateTime;await _context.SaveChangesAsync();TempData["Success"]="Payment confirmed. Your graded assessments are now unlocked.";}else{order.PaymentStatus=PaymentStatus.Failed;await _context.SaveChangesAsync();TempData["Error"]="Payment was not confirmed. No assessment or certificate entitlement was granted.";}return RedirectToAction(nameof(Index));}
    [HttpPost,ValidateAntiForgeryToken,Authorize(Roles=UserRoles.Admin)] public async Task<IActionResult> MarkPaid(int id,string? paymentReference){var order=await _context.Orders.FirstOrDefaultAsync(o=>o.Id==id);if(order is null)return NotFound();order.PaymentStatus=PaymentStatus.Paid;order.PaymentReference=string.IsNullOrWhiteSpace(paymentReference)?order.PaymentReference??$"MANUAL-{Guid.NewGuid():N}"[..20].ToUpperInvariant():paymentReference.Trim();order.PaidAt=_clock.GetUtcNow().UtcDateTime;await _context.SaveChangesAsync();TempData["Success"]=$"Order #{id} marked as paid.";return RedirectToAction(nameof(Index));}
}
